client_secret: ItCPFn5Vj4LVY9Fd3C3zNOTkRtleTCgV
debug: false
disable_auto_update: false
disable_command_execute: false
disable_force_update: false
disable_nat: false
disable_send_query: false
gpu: true
insecure_tls: false
ip_report_period: 1800
report_delay: 3
self_update_period: 0
server: status-no.sdcom.asia:8008
skip_connection_count: false
skip_procs_count: false
temperature: true
tls: false
use_gitee_to_upgrade: false
use_ipv6_country_code: false
uuid: 2d2805fd-a74f-9f79-36b9-cbf65cd455d5
